import type { LayerTemplate, LayerType } from "../types/editor";

export const LAYER_TEMPLATES: Record<LayerType, LayerTemplate> = {
  gradient: {
    type: "gradient",
    label: "Gradient",
    category: "generator",
    description: "Linear gradient from a color ramp texture",
    uniforms: [
      {
        name: "u_gradient",
        type: "gradient",
        label: "Gradient",
        default: [
          { color: "#000000", position: 0 },
          { color: "#330d03", position: 0.15 },
          { color: "#f35a0d", position: 0.35 },
          { color: "#fff2d9", position: 0.6 },
          { color: "#0f3839", position: 0.85 },
          { color: "#000000", position: 1.0 },
        ],
      },
      {
        name: "angle",
        type: "float",
        label: "Angle",
        default: 90,
        min: 0,
        max: 360,
        step: 1,
      },
      {
        name: "offsetX",
        type: "float",
        label: "Offset X",
        default: 0,
        min: -10,
        max: 10,
        step: 0.1,
      },
    ],
    animationUniforms: [
      {
        name: "speed",
        type: "float",
        label: "Speed",
        default: 1.0,
        min: 0,
        max: 3,
        step: 0.01,
      },
    ],
  },

  solid: {
    type: "solid",
    label: "Solid",
    category: "generator",
    description: "Flat solid color fill",
    uniforms: [
      {
        name: "u_color",
        type: "color",
        label: "Color",
        default: "#f35a0d",
      },
    ],
  },

  noise: {
    type: "noise",
    label: "Noise",
    category: "generator",
    description: "Animated simplex noise pattern",
    uniforms: [
      {
        name: "scale",
        type: "float",
        label: "Scale",
        default: 4,
        min: 0.1,
        max: 20,
        step: 0.1,
      },
      {
        name: "octaves",
        type: "float",
        label: "Octaves",
        default: 4,
        min: 1,
        max: 8,
        step: 1,
      },
      {
        name: "persistence",
        type: "float",
        label: "Persistence",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
    animationUniforms: [
      {
        name: "speed",
        type: "float",
        label: "Speed",
        default: 0.5,
        min: 0,
        max: 3,
        step: 0.01,
      },
    ],
  },

  distortion: {
    type: "distortion",
    label: "Distortion",
    category: "distortion",
    description: "Wave-based UV displacement",
    uniforms: [
      {
        name: "waveType",
        type: "select",
        label: "Wave Type",
        default: 0,
        options: [
          { label: "Sine", value: 0 },
          { label: "Square", value: 1 },
          { label: "Triangle", value: 2 },
        ],
      },
      {
        name: "freq",
        type: "float",
        label: "Frequency",
        default: 3,
        min: 0.1,
        max: 20,
        step: 0.1,
      },
      {
        name: "amplitude",
        type: "float",
        label: "Amplitude",
        default: 0.5,
        min: 0,
        max: 5,
        step: 0.01,
      },
      {
        name: "sharpness",
        type: "float",
        label: "Sharpness",
        default: 6.7,
        min: 1,
        max: 50,
        step: 0.1,
      },
      {
        name: "pulseWidth",
        type: "float",
        label: "Pulse Width",
        default: 0.04,
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        name: "skew",
        type: "float",
        label: "Skew",
        default: 0,
        min: -1,
        max: 1,
        step: 0.01,
      },
      {
        name: "direction",
        type: "float",
        label: "Direction",
        default: 45,
        min: 0,
        max: 360,
        step: 1,
      },
    ],
    animationUniforms: [
      {
        name: "speed",
        type: "float",
        label: "Speed",
        default: 1.0,
        min: 0,
        max: 3,
        step: 0.01,
      },
      {
        name: "drift",
        type: "float",
        label: "Drift",
        default: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  },

  grain: {
    type: "grain",
    label: "Grain",
    category: "effect",
    description: "Animated film grain noise",
    uniforms: [
      {
        name: "grainIntensity",
        type: "float",
        label: "Intensity",
        default: 0.02,
        min: 0,
        max: 0.2,
        step: 0.001,
      },
      {
        name: "ditherScale",
        type: "float",
        label: "Block Scale",
        default: 4,
        min: 1,
        max: 16,
        step: 0.5,
      },
    ],
    animationUniforms: [
      {
        name: "speed",
        type: "float",
        label: "Speed",
        default: 50,
        min: 0,
        max: 200,
        step: 1,
      },
    ],
  },

  dither: {
    type: "dither",
    label: "Dither",
    category: "effect",
    description: "Bayer matrix ordered dithering",
    uniforms: [
      {
        name: "levels",
        type: "float",
        label: "Levels",
        default: 16,
        min: 2,
        max: 64,
        step: 1,
      },
      {
        name: "ditherScale",
        type: "float",
        label: "Dither Scale",
        default: 4,
        min: 1,
        max: 16,
        step: 0.5,
      },
    ],
  },

  vignette: {
    type: "vignette",
    label: "Vignette",
    category: "effect",
    description: "Edge darkening effect",
    uniforms: [
      {
        name: "shape",
        type: "select",
        label: "Shape",
        default: 0,
        options: [
          { label: "Rectangular", value: 0 },
          { label: "Radial", value: 1 },
        ],
      },
      {
        name: "vignetteIntensity",
        type: "float",
        label: "Intensity",
        default: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "vignetteRadius",
        type: "float",
        label: "Radius",
        default: 0.4,
        min: 0.01,
        max: 2,
        step: 0.01,
      },
      {
        name: "vignetteSoftness",
        type: "float",
        label: "Softness",
        default: 0.4,
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  },
};

export default LAYER_TEMPLATES;
